//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskComment
    {
        public int ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual TaskDetail TaskDetail { get; set; }
    }
}
