//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetail
    {
       
        
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string TaskName { get; set; }
        public string AssignedUser { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskComment> TaskComments { get; set; }
    }
}
